version: 0.2
phases:
  pre_build:
    commands:
      - |
        sudo apt-get -y update
        sudo apt-get -y install nginx
  build:
    commands:
      - |
        ## Push Container to ECR
        $(aws ecr get-login --no-include-email --region ${AWS_REGION})
        COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        IMAGE_TAG=${COMMIT_HASH:=latest}
        docker build --tag ${REPOSITORY_URI}:latest .
        docker tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:$IMAGE_TAG
        docker push ${REPOSITORY_URI}:latest
        docker push ${REPOSITORY_URI}:$IMAGE_TAG

  post_build:
    commands:
      - |
        ## Create Deploy Spec file
        cat >images.json  <<EOL
        [
          {
              "name": "${SERVICE_NAME}",
              "imageUri": "${REPOSITORY_URI}:$IMAGE_TAG"
          }
        ]
        EOL
artifacts:
  files: images.json
