version: 0.2
env:
  parameter-store:
    user_pool_id: /cloudformation/SpringfieldMunicipality/CarShare/Cognito/UserPoolID
phases:
  pre_build:
    commands:
      - |
        echo $user_pool_id
        $(aws ecr get-login --no-include-email --region ${AWS_REGION})
        COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - |
        ## Push Container to ECR
        docker build --tag ${REPOSITORY_URI}:latest .
        docker tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:$IMAGE_TAG
        docker push ${REPOSITORY_URI}:latest
        docker push ${REPOSITORY_URI}:$IMAGE_TAG
  post_build:
    commands:
      - |
        ## Create Deploy Spec file
        cat >images.json  <<EOL
        [
          {
              "name": "${SERVICE_NAME}",
              "imageUri": "${REPOSITORY_URI}:$IMAGE_TAG"
          }
        ]
        EOL
artifacts:
  files: images.json
